os:
  - linux
  - osx
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
sudo: required
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /etc/lsb-release; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install influxdb; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service influxdb start; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install influxdb; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -sfv /usr/local/opt/influxdb/*.plist ~/Library/LaunchAgents; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl load ~/Library/LaunchAgents/homebrew.mxcl.influxdb.plist; fi'
  - sleep 15
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
