// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP Adresse des Repetier-Servers": {     "en": "IP Adress of Repetier-Server",   "de": "IP Adresse des Repetier-Servers", },
    "Port(default 3344)": {                  "en": "Port(default 3344)",             "de": "Port(Standard 3344)", },
    "API-Key des Repetier-Servers": {        "en": "API-Key of Repetier-Server",     "de": "API-Key von Repetier-Server", },
};